import 'bootstrap/dist/css/bootstrap.css'
import './globals.css'
import Script from 'next/script'
import Navbar from './components/navbar'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"/>
      </body>
    </html>
  )
}
